import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css' 
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub} from "react-icons/ai"
import chibi from '../public/chibi-me.png'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>EM Coding Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl'>EM Coding</h1>
            <ul className='flex items-center'>
              <li className='cursor-pointer'></li>
              <li><a className='bg-black text-white px-4 py-2 rounded-md' href='#'>Resume</a></li>
            </ul>
          </nav>

          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-black font-medium'>Sheridan Melton</h2>
            <h3 className='text-2xl py-2'>Full Stack Web Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>Hello! Welcome to my page my name is Sheridan and I am a freelance Web Developer that can provide you with services to get
              your site or project up and running! If you want to contact me about a project or service you find a link down below.
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a 
            href='https://github.com/XxElijahMxX'>
              <AiFillGithub />
            </a>
            <a
            href='https://www.linkedin.com/in/sheridan-melton-b16287231/'>
            <AiFillLinkedin />
            </a>
            <a
            href='https://twitter.com/ElijahM45'>
            <AiFillTwitterCircle />
            </a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-gray-700 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={chibi} layout='fill' objectFit='cover'/>
          </div>
        </section>

        {/* Next section */}
        <section></section>
        
      </main>
    </>
  )
}
